stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw\creditcard.csv 
    deps:
      - .\data\raw\creditcard.csv
      - .\src\data\make_dataset.py
    params:
      - make_dataset.test_split
      - make_dataset.seed
    outs:
      - .\processed_data\
      
  train_model:
    cmd: python .\src\models\train_model.py .\processed_data\
    deps:
      - .\data\processed\
      - .\src\models\train_model.py
    outs:
      - .\models\
      
  visualize:
    cmd: python .\src\visualization\visualize.py .\models\model.joblib .\processed_data\
    deps:
      - .\data\processed\
      - .\models\model.joblib
      - .\src\visualization\visualize.py
    outs:
      - dvclive

metrics:
  - dvclive\metrics.json

plots:
  - ROC:
      template: simple
      x: fpr
      y:
        dvclive\plots\sklearn\roc\train.json: tpr
        dvclive\plots\sklearn\roc\test.json: tpr
  - Confusion-Matrix:
      template: confusion
      x: actual
      y:
        dvclive\plots\sklearn\cm\train.json: predicted
        dvclive\plots\sklearn\cm\test.json: predicted
  - Precision-Recall:
      template: simple
      x: recall
      y:
        dvclive\plots\sklearn\prc\train.json: precision
        dvclive\plots\sklearn\prc\test.json: precision
